---
title: "Lrp1 ANOVA"
author: "Brendon Smith"
date: "Saturday June 11 2016"
output:
  html_document:
    highlight: pygments
    theme: readable
    toc: yes
subtitle: One-way ANOVA for relative abundance of Lrp1 in the TCMP Nrf1 proteomics mouse liver AP-MS dataset from March 16, 2016. Modified from ANOVA one way ApoE KO tomato soy adipose.
---
# import dataset
```{r}
proteins <- read.table("/Users/brendonsmith/Documents/BWS/Hotamisligil Lab/Nrf/Nrf1 proteomics/TCMP/20160111 Nrf-HA mouse liver AP-MS/20160316 TCMP Nrf1-HA mouse liver other proteins.csv", header=TRUE, sep=",")
attach(proteins)
proteins
```

# anova in aov
```{r}
aov1 <- aov(lrp1~group)
summary(aov1)

```

## multiple comparisons
```{r}
# standard Tukey Honest Significant Differences method
TukeyHSD(aov1)
par(las=2, mar=c(5,8,4,2))
plot(TukeyHSD(aov1))

# a more comprehensive method available in the multcomp package
par(las=1, mar=c(5,4,6,2))
library(multcomp)
tuk <- glht(aov1, linfct=mcp(group="Tukey"))
plot(cld(tuk, level=.05),col="lightgrey")
```

# assumptions

```{r}
plot(aov1)
```

## normality
```{r}
# Shapiro-Wilk W test
shapiro.test(rstandard(aov1))
```

## equality of variances
```{r}
library(car)
leveneTest(lrp1, group)
```

# anova in lm for comparison
```{r}
lm1 <- lm(lrp1~group)
anova(lm1)
```

## regression diagnostics and assumptions
```{r}
library(gvlma)
gvlmalm1 <- gvlma(lm1)
summary(gvlmalm1)
shapiro.test(rstandard(lm1))
cor.test(fitted(lm1), abs(rstandard(lm1)), method="spearman")
library(car)
durbinWatsonTest(lm1)
outlierTest(lm1)
leveneTest(lrp1, group)
```
