---
title: "Ppia SNR ANOVA"
author: "Brendon Smith"
date: "Monday October 31 2016"
output:
  html_document:
    highlight: pygments
    theme: readable
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
subtitle: One-way ANOVA for normalized total summed signal to noise ratio (SNR) of
  Ppia in the TCMP Nrf1 proteomics mouse liver AP-MS dataset from March 16, 2016.
---
# import dataset
```{r}
ProteinData <- read.table("/Users/brendonsmith/Dropbox/Postdoc/Nrf/Nrf1 proteomics/TCMP/20160316 Nrf1-HA mouse liver AP-MS/R/20160316 TCMP Nrf1-HA mouse liver other proteins.csv", header=TRUE, sep=",")
attach(ProteinData)
```
# dataset management
```{r}
orderedgroups <- factor(ProteinData$group, levels = c("lacZ","Nrf1-HA chow","Nrf1-HA chol","Nrf1-HA bort")) # this factor command puts the groups in my preferred order, instead of alphabetically. Note that you must refer to this specific variable to maintain the preferred order. Referring to the original variable name will revert to alphabetical order.
summary(group) # order of groups in original dataset
summary(orderedgroups) # verify desired order of groups
means <- aggregate(Ppia~orderedgroups, ProteinData, mean) # create a vector with the means of each group for boxplot points. It took me a long time to figure out how to get the means in the desired order. I then realized that I was using "group" to define categories in both the raw dataset and the means dataset. Changing the name of the variable containing the rearranged group names to "orderedgroups", and then referring to it later in the code, resolved this issue.
means # verify mean values and ordering

```

# anova in aov
```{r}
aov1 <- aov(Ppia~orderedgroups)
summary(aov1)
```

## multiple comparisons
```{r}
# standard Tukey Honest Significant Differences method
TukeyHSD(aov1)
par(las=2, mar=c(5,15,4,2))
plot(TukeyHSD(aov1))

# a more comprehensive method available in the multcomp package
par(las=1, mar=c(5,4,6,2))
library(multcomp)
library(RColorBrewer) # load RColorBrewer for additional color palettes.
tuk <- glht(aov1, linfct=mcp(orderedgroups="Tukey"))
cld(tuk)
plot(cld(tuk, level=.05), col=brewer.pal(8,"Pastel1")) # "I'm a very vivacious man... Earth tones are so passe. I'm a pastel man."
# the compact letter display is not showing up correctly on these figures.
points(means,pch=23) # add points for group means to the boxplot. Make sure they are in the correct order.
```

## assumptions
```{r}
plot(aov1)
```

### normality
```{r}
# Shapiro-Wilk W test
shapiro.test(rstandard(aov1))
```

### equality of variances
```{r}
library(car)
leveneTest(Ppia, orderedgroups)
```

# anova in lm for comparison
```{r}
lm1 <- lm(Ppia~orderedgroups)
anova(lm1)
```

## regression diagnostics and assumptions
```{r}
library(gvlma)
gvlmalm1 <- gvlma(lm1)
summary(gvlmalm1)
shapiro.test(rstandard(lm1))
cor.test(fitted(lm1), abs(rstandard(lm1)), method="spearman")
library(car)
durbinWatsonTest(lm1)
outlierTest(lm1)
leveneTest(Ppia, orderedgroups)
```

<!-- # anova in aov log -->
<!-- ```{r} -->

<!-- meanslog <- aggregate(log(Ppia)~orderedgroups, ProteinData, mean, levels = c("lacZ","Nrf1-HA chow","Nrf1-HA chol","Nrf1-HA bort")) # recalculate means for log transformed data -->
<!-- meanslog # verify mean values and ordering -->

<!-- aovlog <- aov(log(Ppia)~orderedgroups) -->
<!-- summary(aovlog) -->
<!-- ``` -->

<!-- ## multiple comparisons log -->
<!-- ```{r} -->
<!-- # standard Tukey Honest Significant Differences method -->
<!-- TukeyHSD(aovlog) -->
<!-- par(las=2, mar=c(5,8,4,2)) -->
<!-- plot(TukeyHSD(aovlog)) -->

<!-- # a more comprehensive method available in the multcomp package -->
<!-- par(las=1, mar=c(5,4,6,2)) -->
<!-- library(multcomp) -->
<!-- library(RColorBrewer) # load RColorBrewer for additional color palettes. -->
<!-- tuk <- glht(aovlog, linfct=mcp(orderedgroups="Tukey")) -->

<!-- plot(cld(tuk, level=.05), col=brewer.pal(8,"Pastel1")) # "I'm a very vivacious man... Earth tones are so passe. I'm a pastel man." -->
<!-- points(meanslog,pch=23) # add points for group means to the boxplot. Make sure they are in the correct order. -->
<!-- ``` -->

<!-- ## assumptions log -->
<!-- ```{r} -->
<!-- plot(aovlog) -->
<!-- ``` -->

<!-- ### normality log -->
<!-- ```{r} -->
<!-- # Shapiro-Wilk W test -->
<!-- # Log transformation does not completely normalize data, but considering the non-significant ANOVA result, I will stop here. -->
<!-- shapiro.test(rstandard(aovlog)) -->
<!-- ``` -->

<!-- ### equality of variances log -->
<!-- ```{r} -->
<!-- library(car) -->
<!-- leveneTest(aovlog) -->
<!-- ``` -->

<!-- # anova in lm for comparison log -->
<!-- ```{r} -->
<!-- lmlog <- lm(log(Ppia)~orderedgroups) -->
<!-- anova(lmlog) -->
<!-- ``` -->

<!-- ## regression diagnostics and assumptions log -->
<!-- ```{r} -->
<!-- library(gvlma) -->
<!-- gvlmalmlog <- gvlma(lmlog) -->
<!-- summary(gvlmalmlog) -->
<!-- shapiro.test(rstandard(gvlmalmlog)) -->
<!-- cor.test(fitted(lmlog), abs(rstandard(lmlog)), method="spearman") -->
<!-- library(car) -->
<!-- durbinWatsonTest(lmlog) -->
<!-- outlierTest(lmlog) -->
<!-- leveneTest(log(Ppia), orderedgroups) -->
<!-- ``` -->